import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../components/NavBar/Navbar'
import Header from '../components/Header/Header'
import CardBody from '../components/CardBody/CardBody'
import Footer from '../components/Footer/Footer'

export default function Contact() {

    return (
        <div className={" bg-gradient-to-b from-neutral-700 to-neutral-200"} >
            <Head>
                <title>smoke / mirrors</title>
                < meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/images/abb-logo.png" />
            </Head>
            < Navbar />

            <div className={"container mx-auto px-5 lg-px-20"}>

            </div>
            < Footer />

        </div>
    )
}