import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../components/NavBar/Navbar'
import Header from '../components/Header/Header'
import CardBody from '../components/CardBody/CardBody'
import Footer from '../components/Footer/Footer'
import ContactForm from '../components/ContactForm/ContactForm'
import ContactBody from '../components/ContactBody/ContactBody'


export default function Contact() {

    return (
        <div className={" bg-gradient-to-b from-neutral-700 to-neutral-200"} >
            <Head>
                <title>smoke / mirrors</title>
                < meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/images/abb-logo.png" />
            </Head>
            < Navbar />

            <div className={"container mx-auto px-5 lg-px-20 pt-10"}>
                <div className='text-9xl pb-10 text-center'>Contact</div>
                <div className='mx-auto p-10 flex flex-wrap'>
                    <div className='w-full md:w-1/2 text-center'>
                        <div className='text-5xl'>Send us a message</div>
                        <ContactForm />
                    </div>
                    <div className='w-full md:w-1/2'>
                        <ContactBody />
                    </div>
                </div>

            </div>
            < Footer />

        </div>
    )
}